version: 2
jobs:
  build:
    working_directory: ~/badge
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          command: |
            python2 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            fab run_tests
